import type { ThemeSettings } from '../api/theme';

export const themePresets: Record<string, ThemeSettings> = {
  light: {
    storeName: 'Light Store',
    logoUrl: '',
    darkMode: false,
    primaryColor: '#1976d2',
    secondaryColor: '#dc004e',
    fontFamily: 'Roboto, sans-serif',
    fontSize: 16,
    fontWeight: 400,
    spacingScale: 8,
    borderRadius: 2,
    maxWidth: 'lg',
    homepageLayout: 'hero',
    productCardVariant: 'compact',
    categoryStyle: 'tabs',
    showSidebar: true,
    stickyHeader: false,
  },
  dark: {
    storeName: 'Dark Store',
    logoUrl: '',
    darkMode: true,
    primaryColor: '#90caf9',
    secondaryColor: '#f48fb1',
    fontFamily: 'Open Sans, sans-serif',
    fontSize: 16,
    fontWeight: 400,
    spacingScale: 8,
    borderRadius: 2,
    maxWidth: 'lg',
    homepageLayout: 'grid',
    productCardVariant: 'detailed',
    categoryStyle: 'dropdown',
    showSidebar: true,
    stickyHeader: true,
  },
  elegant: {
    storeName: 'Elegant Mode',
    logoUrl: '',
    darkMode: false,
    primaryColor: '#6a1b9a',
    secondaryColor: '#ffab00',
    fontFamily: 'Inter, sans-serif',
    fontSize: 17,
    fontWeight: 500,
    spacingScale: 10,
    borderRadius: 10,
    maxWidth: 'xl',
    homepageLayout: 'list',
    productCardVariant: 'compact',
    categoryStyle: 'tabs',
    showSidebar: false,
    stickyHeader: false,
  },
  gaming: {
    storeName: 'Gaming Shop',
    logoUrl: '',
    darkMode: true,
    primaryColor: '#00e5ff',
    secondaryColor: '#d500f9',
    fontFamily: 'Orbitron, sans-serif',
    fontSize: 15,
    fontWeight: 700,
    spacingScale: 12,
    borderRadius: 16,
    maxWidth: 'full',
    homepageLayout: 'hero',
    productCardVariant: 'detailed',
    categoryStyle: 'dropdown',
    showSidebar: true,
    stickyHeader: true,
  },
};
